// Auto-generated from HFU staff directory (Faculty I professors)
// Source: https://www.hs-furtwangen.de/en/staff-directory?tx_solr%5Bfilter%5D%5B0%5D=fFaC%3A386&tx_solr%5Bfilter%5D%5B1%5D=fFnC%3A239

export const professorContacts = [
  {
    name: "Prof. Dr. Eduard Heindl",
    role: "Professor",
    department: "Faculty I: Computer Science & Applications",
    email: "eduard.heindl@hs-furtwangen.de",
    phone: "+49 7723 920-2403",
    officeLocation: "Building I, Room 202",
    officeHours: "By appointment",
    tags: ["professor", "ibs", "thesis", "mathematics"],
    relevantSemesters: [1, 4, 7],
  },
  {
    name: "Prof. Dr. Guido Siestrup",
    role: "Professor",
    department: "Faculty I: Computer Science & Applications",
    email: "guido.siestrup@hs-furtwangen.de",
    phone: "+49 7723 920-2240",
    officeLocation: "Building I, Room 206",
    officeHours: "By appointment",
    tags: ["professor", "ibs"],
    relevantSemesters: [2, 4, 5, 7],
  },
  {
    name: "Prof. Dr. Holger Ziekow",
    role: "Professor",
    department: "Faculty I: Computer Science & Applications",
    email: "holger.ziekow@hs-furtwangen.de",
    phone: "+49 7723 920-2938",
    officeLocation: "Building H, Room 004",
    officeHours: "By arrangement",
    tags: [
      "professor",
      "ibs",
      "dean-of-studies",
      "international",
      "business-informatics",
      "thesis",
    ],
    relevantSemesters: [1, 2, 3, 4, 5, 6, 7],
  },
  {
    name: "Prof. Dr. Jürgen Weiner",
    role: "Professor",
    department: "Faculty I: Computer Science & Applications",
    email: "juergen.weiner@hs-furtwangen.de",
    phone: "+49 7723 920-2242",
    officeLocation: "Building I, Room 201",
    officeHours: "By appointment",
    tags: ["professor", "ibs", "SAP"],
    relevantSemesters: [3, 5, 6, 7],
  },
  {
    name: "Prof. Dr. Martin Knahl",
    role: "Professor",
    department: "Faculty I: Computer Science & Applications",
    email: "martin.knahl@hs-furtwangen.de",
    phone: "+49 7723 920-2241",
    officeLocation: "Building C, Room 205; Building I, Room 201",
    officeHours: "By appointment",
    tags: ["professor", "ibs"],
    relevantSemesters: [1, 4, 5, 6, 7],
  },
  {
    name: "Prof. Dr. Monika Frey-Luxemburger",
    role: "Professor",
    department: "Faculty I: Computer Science & Applications",
    email: "monika.frey-luxemburger@hs-furtwangen.de",
    phone: "+49 7723 920-2427",
    officeLocation: "Building H, Room 004",
    officeHours: "By appointment",
    tags: ["professor", "ibs", "thesis"],
    relevantSemesters: [2, 4, 5, 6, 7],
  },
  {
    name: "Prof. Dr. Oliver Taminé",
    role: "Professor",
    department: "Faculty I: Computer Science & Applications",
    email: "oliver.tamine@hs-furtwangen.de",
    phone: "+49 7723 920-2913",
    officeLocation: "Building I, Room 209",
    officeHours: "By appointment",
    tags: ["professor", "ibs", "deputy-dean", "vice-dean"],
    relevantSemesters: [5, 7],
  },
  {
    name: "Prof. Dr. Pavel Rawe",
    role: "Professor",
    department: "Faculty I: Computer Science & Applications",
    email: "pavel.rawe@hs-furtwangen.de",
    phone: "+49 7723-920-2950",
    officeLocation: "Building I, Room 208",
    officeHours: "By appointment",
    tags: [
      "professor",
      "ibs",
      "dean-of-studies",
      "deputy-dean",
      "international",
      "business-informatics",
      "thesis",
      "internship",
    ],
    relevantSemesters: [1, 2, 3, 4, 5, 6, 7],
  },
  {
    name: "Prof. Dr. rer. pol. Simon Albrecht",
    role: "Professor",
    department: "Faculty I: Computer Science & Applications",
    email: "simon.albrecht@hs-furtwangen.de",
    tags: ["professor", "ibs", "business-informatics"],
    relevantSemesters: [1, 5, 6, 7],
  },

  {
    name: "Prof. Dr.-Ing. Stefan Noll",
    role: "Professor",
    department: "Faculty I: Computer Science & Applications",
    email: "stefan.noll@hs-furtwangen.de",
    phone: "+49 7723 920-2713",
    officeLocation: "Building I, Room 205",
    officeHours: "By appointment",
    tags: ["professor", "ibs", "software-project", "thesis"],
    relevantSemesters: [2, 5, 6, 7],
  },
]
